// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjECiB5b5STbQIJvDe9SRm-cTOm1TOLkM',
    appId: '1:796970708043:web:8132dca4aecd6aa6f231ce',
    messagingSenderId: '796970708043',
    projectId: 'settle-playground',
    authDomain: 'settle-playground.firebaseapp.com',
    databaseURL: 'https://settle-playground-default-rtdb.firebaseio.com',
    storageBucket: 'settle-playground.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjkqncmtG_xwdMkTPLJrN9zScigtnSmo',
    appId: '1:796970708043:android:4f144f136cc64dbbf231ce',
    messagingSenderId: '796970708043',
    projectId: 'settle-playground',
    databaseURL: 'https://settle-playground-default-rtdb.firebaseio.com',
    storageBucket: 'settle-playground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHV6Ovn122HinUt1RWqkXus9m77lrVYdM',
    appId: '1:796970708043:ios:87a1a93503860e84f231ce',
    messagingSenderId: '796970708043',
    projectId: 'settle-playground',
    databaseURL: 'https://settle-playground-default-rtdb.firebaseio.com',
    storageBucket: 'settle-playground.appspot.com',
    iosClientId: '796970708043-lv9eokk4c51bog46jhv2u5pv3468jvkd.apps.googleusercontent.com',
    iosBundleId: 'com.example.Settle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHV6Ovn122HinUt1RWqkXus9m77lrVYdM',
    appId: '1:796970708043:ios:f0c2e3db46c1631ef231ce',
    messagingSenderId: '796970708043',
    projectId: 'settle-playground',
    databaseURL: 'https://settle-playground-default-rtdb.firebaseio.com',
    storageBucket: 'settle-playground.appspot.com',
    iosClientId: '796970708043-0vpp9pqcrv81hpgo4hrh3pa13v1hr8s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
